name: Build and publish latest image

on:
  workflow_dispatch:

permissions: read-all

env:
  IMAGE_NAME: sae-object-detector
  DOCKERHUB_USERNAME: starwit
  DOCKERHUB_ORG: starwitorg  

jobs:
  build:
    name: "Build and run docker image"
    runs-on: [self-hosted, linux, X64]

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Set up python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: '2.2.1'
        plugins: poetry-plugin-export

    - name: Export requirements
      run: |
        poetry export -o requirements.txt --without-hashes
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: build and push docker
      run: |
        echo "DOCKER_VERSION=$(cat pyproject.toml | grep "version" | head -1 | cut -d'=' -f2 | xargs echo -n)"  >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        sbom: true
        provenance: mode=max
        push: true
        cache-from: type=local,src=/home/githubrunner/.buildx-cache
        cache-to: type=local,dest=/home/githubrunner/.buildx-cache        
        tags: ${{ env.DOCKERHUB_ORG }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_VERSION }}-${{ github.run_number }}


